FROM node:20-alpine AS base
WORKDIR /app

FROM base AS dev
COPY trexgym-api/package*.json ./
RUN npm ci
COPY trexgym-api/ ./
EXPOSE 3000
CMD ["npm", "run", "start:dev"]

FROM base AS build
COPY trexgym-api/package*.json ./
RUN npm ci
COPY trexgym-api/ ./
RUN npm run build

FROM node:20-alpine AS prod
WORKDIR /app
ENV NODE_ENV=production
COPY trexgym-api/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/main.js"]
